from __future__ import annotations

import csv
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from .config import Settings, build_settings
from .console_notify import send_console_notification
from .errors import short_error
from .watchlist import normalize_symbol


PREMARKET_WATCH_CODES_NAME = "watch_codes_premarket.txt"


@dataclass(frozen=True)
class PremarketWatchCandidate:
    """盘前推荐监控的候选股票。"""

    symbol: str
    signal_date: date
    previous_close: float
    close: float
    gain_pct: float


def premarket_watch_codes_path(settings: Settings) -> Path:
    """返回盘前推荐专用观察池文件。"""
    return settings.watch_codes_file.with_name(PREMARKET_WATCH_CODES_NAME)


def generate_premarket_watch_codes(
    settings: Settings | None = None,
    symbols: list[str] | None = None,
    max_symbols: int | None = None,
    top_count: int = 50,
    lookback_days: int = 20,
    batch_size: int = 100,
    feed: str = "sip",
) -> list[PremarketWatchCandidate]:
    """按最近已收盘交易日涨幅排名生成盘前推荐股票池。"""
    from .watchlist_generator import fetch_daily_bars, load_tradable_symbols

    settings = settings or build_settings()
    now_et = datetime.now(ZoneInfo(settings.market_timezone))
    symbol_pool = symbols or load_tradable_symbols(max_symbols=max_symbols)
    if max_symbols is not None:
        symbol_pool = symbol_pool[:max_symbols]

    print(f"开始生成盘前 watchcode：symbols={len(symbol_pool)} feed={feed} top_count={top_count}", flush=True)
    bars_by_symbol = fetch_daily_bars(symbol_pool, now_et, lookback_days, batch_size, feed)
    candidates = screen_premarket_top_gain_candidates(bars_by_symbol, now_et, top_count=top_count)
    watch_path = write_premarket_watch_codes(premarket_watch_codes_path(settings), candidates, top_count=top_count)
    report_path = write_premarket_candidate_report(settings.output_dir, candidates)

    print(f"盘前 watchcode 生成完成：{len(candidates)} 个候选，已写入 {watch_path}", flush=True)
    print(f"盘前候选 CSV: {report_path}", flush=True)
    send_console_notification(
        "\n".join(
            [
                "【盘前 watchcode 生成完成】",
                "结论：盘前推荐观察池已更新。",
                "动作：后续盘前监控会基于该文件做 MA5 推荐提醒；不会下单。",
                "",
                "生成结果",
                f"- 候选数量：{len(candidates)}",
                f"- 排名规则：最近已收盘交易日涨幅 Top {top_count}",
                f"- 观察文件：{watch_path}",
                f"- 候选 CSV：{report_path}",
            ]
        ),
        context="premarket watchcode generated",
        settings=settings,
    )
    return candidates


def screen_premarket_top_gain_candidates(
    bars_by_symbol: dict[str, list[DailyBar]],
    now_et: datetime,
    *,
    top_count: int = 50,
) -> list[PremarketWatchCandidate]:
    """选出最近已收盘交易日涨幅最高的前 N 只股票。"""
    from .watchlist_generator import latest_completed_signal_date

    signal_date = latest_completed_signal_date(bars_by_symbol, now_et)
    if signal_date is None:
        return []

    candidates: list[PremarketWatchCandidate] = []
    for symbol, bars in bars_by_symbol.items():
        candidate = evaluate_premarket_top_gain_candidate(symbol, bars, now_et, signal_date)
        if candidate:
            candidates.append(candidate)
    return sorted(candidates, key=lambda item: item.gain_pct, reverse=True)[:top_count]


def evaluate_premarket_top_gain_candidate(
    symbol: str,
    bars: list[DailyBar],
    now_et: datetime,
    signal_date: date,
) -> PremarketWatchCandidate | None:
    """计算单股最近完成交易日涨幅；无效日线直接跳过。"""
    from .watchlist_generator import is_completed_bar

    completed = [bar for bar in sorted(bars, key=lambda item: item.date) if is_completed_bar(bar, now_et)]
    signal_index = next((index for index, bar in enumerate(completed) if bar.date == signal_date), None)
    if signal_index is None or signal_index < 1:
        return None

    signal = completed[signal_index]
    previous = completed[signal_index - 1]
    if previous.close <= 0 or signal.close <= 0:
        return None

    return PremarketWatchCandidate(
        symbol=normalize_symbol(symbol),
        signal_date=signal.date,
        previous_close=previous.close,
        close=signal.close,
        gain_pct=signal.close / previous.close - 1.0,
    )


def write_premarket_watch_codes(
    path: Path,
    candidates: list[PremarketWatchCandidate],
    *,
    top_count: int = 50,
) -> Path:
    """写出盘前推荐专用观察池。"""
    lines = [
        "# Auto-generated by watchcode_premarket.py",
        f"# Rules: latest completed trading day gain top {top_count}",
    ]
    if candidates:
        lines.append(f"# signal_date={candidates[0].signal_date:%Y-%m-%d}")
    lines.extend(candidate.symbol for candidate in candidates)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_premarket_candidate_report(output_dir: Path, candidates: list[PremarketWatchCandidate]) -> Path:
    """写出盘前候选诊断 CSV。"""
    output_dir.mkdir(parents=True, exist_ok=True)
    day = candidates[0].signal_date if candidates else datetime.now().date()
    path = output_dir / f"premarket_watch_candidates_{day:%Y-%m-%d}.csv"
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["symbol", "signal_date", "previous_close", "close", "gain_pct"],
        )
        writer.writeheader()
        for candidate in candidates:
            writer.writerow(candidate.__dict__)
    return path


def read_premarket_watch_metadata(path: Path) -> tuple[date | None, list[str]]:
    """读取盘前 watchcode 的信号日和股票列表。"""
    if not path.exists():
        return None, []

    signal_day: date | None = None
    symbols: list[str] = []
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("# signal_date="):
            try:
                signal_day = date.fromisoformat(line.split("=", 1)[1].strip())
            except ValueError as exc:
                print(f"盘前 watchcode 日期无效，忽略：{short_error(exc)}", flush=True)
            continue
        if line.startswith("#"):
            continue
        symbols.append(normalize_symbol(line))
    return signal_day, symbols
